stages:
  - deploy

deploy_prod:
  stage: deploy
  tags:
    - ec2-runner
  script:
    - cd /home/ubuntu/Leads-Rubix-CRM
    - git checkout prod
    - git pull origin prod
    - pnpm install --no-frozen-lockfile
    - PORT=3000 pnpm run build
    - pm2 restart api-server
  rules:
    - if: $CI_COMMIT_BRANCH == "prod"
