// src/utils/countries.js

const countryList = [
  { name: 'India', code: 'IN', dial: '+91' },
  { name: 'United States', code: 'US', dial: '+1' },
  { name: 'United Kingdom', code: 'GB', dial: '+44' },
  { name: 'Canada', code: 'CA', dial: '+1' },
  { name: 'Australia', code: 'AU', dial: '+61' },
  { name: 'United Arab Emirates', code: 'AE', dial: '+971' },
  { name: 'Singapore', code: 'SG', dial: '+65' },
  { name: 'Saudi Arabia', code: 'SA', dial: '+966' },
  { name: 'Germany', code: 'DE', dial: '+49' },
  { name: 'France', code: 'FR', dial: '+33' },
  { name: 'South Africa', code: 'ZA', dial: '+27' },
  { name: 'Japan', code: 'JP', dial: '+81' },
  { name: 'New Zealand', code: 'NZ', dial: '+64' },
  { name: 'Malaysia', code: 'MY', dial: '+60' },
  { name: 'Ireland', code: 'IE', dial: '+353' },
  { name: 'Italy', code: 'IT', dial: '+39' },
  { name: 'Netherlands', code: 'NL', dial: '+31' },
  { name: 'Spain', code: 'ES', dial: '+34' },
  { name: 'Switzerland', code: 'CH', dial: '+41' },
  { name: 'Sweden', code: 'SE', dial: '+46' },
  { name: 'Norway', code: 'NO', dial: '+47' },
  { name: 'Denmark', code: 'DK', dial: '+45' },
  { name: 'Finland', code: 'FI', dial: '+358' },
  { name: 'Brazil', code: 'BR', dial: '+55' },
  { name: 'Mexico', code: 'MX', dial: '+52' },
  { name: 'Russia', code: 'RU', dial: '+7' },
  { name: 'China', code: 'CN', dial: '+86' },
  { name: 'Hong Kong', code: 'HK', dial: '+852' },
  { name: 'Taiwan', code: 'TW', dial: '+886' },
  { name: 'South Korea', code: 'KR', dial: '+82' },
  { name: 'Turkey', code: 'TR', dial: '+90' },
  { name: 'Egypt', code: 'EG', dial: '+20' },
  { name: 'Nigeria', code: 'NG', dial: '+234' },
  { name: 'Kenya', code: 'KE', dial: '+254' },
  { name: 'Bangladesh', code: 'BD', dial: '+880' },
  { name: 'Pakistan', code: 'PK', dial: '+92' },
  { name: 'Sri Lanka', code: 'LK', dial: '+94' },
  { name: 'Nepal', code: 'NP', dial: '+977' },
  { name: 'Thailand', code: 'TH', dial: '+66' },
  { name: 'Vietnam', code: 'VN', dial: '+84' },
  { name: 'Indonesia', code: 'ID', dial: '+62' },
  { name: 'Philippines', code: 'PH', dial: '+63' },
  { name: 'Argentina', code: 'AR', dial: '+54' },
  { name: 'Colombia', code: 'CO', dial: '+57' },
  { name: 'Peru', code: 'PE', dial: '+51' },
  { name: 'Chile', code: 'CL', dial: '+56' },
  { name: 'Austria', code: 'AT', dial: '+43' },
  { name: 'Belgium', code: 'BE', dial: '+32' },
  { name: 'Poland', code: 'PL', dial: '+48' },
  { name: 'Greece', code: 'GR', dial: '+30' }
];

module.exports = {
  countryList,
  countryNames: countryList.map(c => ({ value: c.name, label: c.name })),
  dialingCodes: countryList.map(c => ({ value: c.dial, label: `${c.dial} (${c.name})` }))
};
